import {DatabaseSync} from 'node:sqlite';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
const dir=mkdtempSync(path.join(tmpdir(),'borrow-test-')),port=43129,base=`http://127.0.0.1:${port}`;
let child,cookie='';
async function start(){child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port),DATA_DIR:dir,HOST:'127.0.0.1',INVITATION_CODE:'test-invitation'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',code=>reject(new Error('Server exited '+code)));});}
async function stop(){if(child.exitCode!==null)return;const done=new Promise(r=>child.once('exit',r));child.kill();await done;}
async function req(url,method='GET',data,headers={}){const response=await fetch(base+url,{method,headers:{'Content-Type':'application/json',Cookie:cookie,...headers},body:data?JSON.stringify(data):undefined});return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')};}
test('borrowing lifecycle, conflict handling, validation, pagination and persistence',async()=>{try{
const legacy=new DatabaseSync(path.join(dir,'borrow.sqlite'));
legacy.exec("CREATE TABLE records(id TEXT PRIMARY KEY,item TEXT NOT NULL,borrower TEXT NOT NULL,contact TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',quantity INTEGER NOT NULL,borrow_date TEXT NOT NULL,due_date TEXT,returned_date TEXT,photo TEXT,thumb TEXT,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);INSERT INTO records(id,item,borrower,quantity,borrow_date,returned_date,created_at) VALUES('legacy','Old record','Old borrower',1,'2020-01-01','2020-01-02','2020-01-01');");
legacy.close();await start();
assert.equal((await req('/api/records')).status,401);
assert.equal((await req('/photos/123.jpg')).status,401);
const account={name:'Employee One',username:'employee.one',password:'Long-test-password',invitation:'test-invitation',remember:true};
assert.equal((await req('/api/auth/register','POST',{...account,invitation:'wrong'})).status,403);
const registration=await req('/api/auth/register','POST',account);assert.equal(registration.status,200);assert.match(registration.cookie,/HttpOnly/);assert.match(registration.cookie,/SameSite=Strict/);assert.match(registration.cookie,/Max-Age=2592000/);cookie=registration.cookie.split(';')[0];const firstUser=registration.data.user;
const migrated=(await req('/api/records?status=archived')).data.rows[0];assert.equal(migrated.item,'Old record');assert.equal(migrated.creator,null);
assert.equal((await req('/api/auth/register','POST',{...account,username:'EMPLOYEE.ONE'})).status,409);
assert.equal((await req('/api/auth/me')).data.user.id,firstUser.id);
const record={id:randomUUID(),item:'<img src=x onerror=alert(1)>',borrower:'ทดสอบ',quantity:2,borrow_date:'2026-09-01',due_date:'2026-09-20'};
assert.equal((await req('/api/records','POST',{...record,quantity:-1})).status,400);
assert.equal((await req('/api/records','POST',{...record,due_date:'2026-08-01'})).status,400);
assert.equal((await req('/api/records','POST',record,{Origin:'https://other.example'})).status,403);
assert.equal((await req('/api/records','POST',{...record,image:'data:image/jpeg;base64,YWJj',thumbnail:'data:image/jpeg;base64,YWJj'})).status,400);
assert.equal((await req('/api/records','POST',record)).status,201);
assert.equal((await req('/api/records','POST',record)).status,200);
assert.equal((await req('/api/records')).data.total,1);
assert.equal((await req('/api/records')).data.rows[0].created_by,firstUser.id);
assert.equal((await req('/api/records/'+record.id+'/activity')).data.rows.length,1);
const second=await req('/api/auth/register','POST',{...account,name:'Employee Two',username:'employee.two'});cookie=second.cookie.split(';')[0];
const update={...record,item:'แก้ไขชื่อ',version:1};assert.equal((await req('/api/records/'+record.id,'PATCH',update)).status,200);
assert.equal((await req('/api/records/'+record.id,'PATCH',update)).status,409);
assert.equal((await req('/api/records')).data.total,1);
assert.equal((await req('/api/records/'+record.id,'PATCH',{action:'return',version:2})).status,200);
assert.equal((await req('/api/records')).data.total,0);
assert.equal((await req('/api/records?status=returned')).data.total,1);
assert.equal((await req('/api/records/'+record.id,'PATCH',{action:'reopen',version:3})).status,200);
const history=(await req('/api/records/'+record.id+'/activity')).data.rows;
assert.deepEqual(history.map(x=>x.action),['reopen','return','edit','create']);
assert.equal(history[0].employee_id,second.data.user.id);assert.equal(history[3].employee_id,firstUser.id);
assert.equal((await req('/api/records')).data.rows[0].created_by,firstUser.id);
for(let i=0;i<21;i++)assert.equal((await req('/api/records','POST',{...record,id:randomUUID(),item:'รายการ '+i})).status,201);
assert.equal((await req('/api/records')).data.rows.length,20);assert.equal((await req('/api/records?page=2')).data.rows.length,2);
assert.equal((await req('/api/records?q='+encodeURIComponent('แก้ไขชื่อ'))).data.total,1);
await stop();await start();assert.equal((await req('/api/records')).data.total,22);
const oldCookie=cookie;
assert.equal((await req('/api/auth/logout','POST',{})).status,200);
assert.equal((await req('/api/records')).status,401);
assert.equal((await req('/api/auth/login','POST',{username:account.username,password:'incorrect-password'})).status,401);
const login=await req('/api/auth/login','POST',account);assert.equal(login.status,200);cookie=login.cookie.split(';')[0];assert.notEqual(cookie,oldCookie);
assert.equal((await req('/api/records')).status,200);
assert.equal((await req('/api/records','GET',null,{Cookie:oldCookie})).status,401);
const page=await fetch(base);assert.equal(page.status,200);assert.match(page.headers.get('Content-Security-Policy'),/script-src 'self'/);
}finally{await stop();rmSync(dir,{recursive:true,force:true});}});
